# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-27 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('descricao', models.TextField()),
                ('escolha', models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'N\xc3O')], max_length=10)),
                ('valor', models.FloatField(help_text='Valor do servi\xe7o')),
            ],
            options={
                'verbose_name_plural': 'Servi\xe7os dispon\xedveis na plataforma',
            },
        ),
    ]
